[package]
org = "ballerinax"
name = "ai.pgvector"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["AI/Vector Database", "Cost/Free", "Vendor/PostgreSQL", "Area/AI & Machine Learning", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.pgvector"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true
